language: java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhook.pluginwiki.tk/travis.php
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
after_success:
  - wget https://raw.githubusercontent.com/brainsynder-Dev/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/brainsynder-Dev/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
