name: SimplePets
main: simplepets.brainsynder.PetCore
version: ${project.version}
depends: [SimpleAPI]
softdepend: [WorldGuard, Vault]
loadbefore: [Citizens, mcMMO, ProtocolSupport, PlotSquared]
authors: [brainsynder, Thatsmusic99]
commands:
    pet:
        description: Main SimplePets command
        aliases: [pets, simplepets, simplepet]
permissions:
    Pet.*:
        default: false
        children:
            Pet.type.*: true
            Pet.name.*: true
            Pet.PetToMount: true
            Pet.PetToHat: true
            Pet.commands.reload: true
            Pet.itemstorage: true
    Pet.commands.*:
        default: false
        children:
            Pet.commands.summon.other: true
            Pet.commands.help: true
            Pet.commands.list: true
    Pet.type.*:
        default: false
        children:
            Pet.type.passive: true
            Pet.type.hostile: true
    Pet.name.*:
        default: false
        children:
            Pet.name.bypass: true
            Pet.name.bypassLimit: true
            Pet.name: true
            Pet.name.color: true
            Pet.name.magic: true
    Pet.type.passive:
        default: false
        children:
            Pet.type.bat: true
            Pet.type.chicken: true
            Pet.type.cow: true
            Pet.type.giant: true
            Pet.type.horse: true
            Pet.type.irongolem: true
            Pet.type.mooshroom: true
            Pet.type.ocelot: true
            Pet.type.pig: true
            Pet.type.rabbit: true
            Pet.type.sheep: true
            Pet.type.snowman: true
            Pet.type.villager: true
            Pet.type.wolf: true
            Pet.type.squid: true
            Pet.type.polarbear: true
            Pet.type.llama: true
            Pet.type.zombiehorse: true
            Pet.type.skeletonhorse: true
            Pet.type.armorstand: true
            Pet.type.parrot: true
            Pet.type.mule: true
    Pet.type.hostile:
        default: false
        children:
            Pet.type.blaze: true
            Pet.type.creeper: true
            Pet.type.enderman: true
            Pet.type.pigman: true
            Pet.type.silverfish: true
            Pet.type.skeleton: true
            Pet.type.spider: true
            Pet.type.zombie: true
            Pet.type.ghast: true
            Pet.type.endermite: true
            Pet.type.wither: true
            Pet.type.witch: true
            Pet.type.guardian: true
            Pet.type.elderguardian: true
            Pet.type.slime: true
            Pet.type.stray: true
            Pet.type.vex: true
            Pet.type.evoker: true
            Pet.type.vindicator: true
            Pet.type.husk: true
            Pet.type.magmacube: true
            Pet.type.witherskeleton: true
            Pet.type.shulker: true
            Pet.type.cavespider: true
            Pet.type.illusioner: true