name: ❓ Simple Question
description: You have a question you would like answered
title: "[Question]: "
labels: ["question"]
assignees:
  - brainsynder-Dev
  - Thatsmusic99
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">So you have a question you would like to answered? Perfect fill out the info below and we will look into adding it in if possible.</div>

  - type: dropdown
    id: issue-related
    attributes:
      label: Issue Related
      description: Is the question you are asking about related to a current issue?
      options:
        - "YES"
        - "NO"
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: What is your question?
      description: |
        In the area below please put your question. [ REQUIRED ]

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
      placeholder: I have an idea!
    validations:
      required: true

  - type: checkboxes
    id: checked
    attributes:
      label: Did you search for answers?
      description: Have you searched previous questions/issues for an answer?
      options:
        - label: I have searched on [GITHUB](https://github.com/brainsynder-Dev/SimplePets/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for similar answers
          required: false
        - label: I have searched on [DISCORD](https://discord.gg/TzhnW8xtsR) for answers
          required: false
        - label: I have searched the [WIKI](https://brainsynder.gitbook.io/simplepets/faq) for answers
          required: false
